version: '3.8'

services:
  postgres:
    image: postgres:12.8
    restart: always
    environment:
      POSTGRES_DB: cloths
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: